### ISSUE TITLE
Trigger an optimism issue

### ISSUE THREAD

**Issue by GrapeBaBa** [merklefruit/op-up#1]
Met this issue when exec `make devnet` https://github.com/ethereum-optimism/optimism/issues/3087

**Comment by merklefruit** [comment]
@GrapeBaBa Thanks for reporting! 
Just as a heads up: this project is still WIP and doesn't work yet.

I am currently a bit short on free time so had to pause it for some time 😞

**Comment by GrapeBaBa** [comment]
Found the issue, the node version must be `16.16.0`
